### ISSUE TITLE
Hoàn thành tìm hiểu về khái niệm và lợi ích khi sử dụng Circle CI

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#14]
Hoàn thành tìm hiểu về Circle CI và Docker

**Comment by mytranchi** [comment]
### Tìm hiểu về Circle CI
#### Circle CI là gì
CircleCI là một công cụ liên tục tích hợp (Continuous Integration - CI) và liên tục triển khai (Continuous Deployment - CD) được cung cấp dưới dạng dịch vụ trên đám mây (cloud) để giúp tự động hóa quá trình xây dựng, kiểm thử và triển khai ứng dụng phần mềm.

CircleCI cho phép các nhà phát triển và nhóm phát triển tích hợp mã nguồn, kiểm thử, và triển khai ứng dụng tự động bằng cách cung cấp một nền tảng liên tục tích hợp và triển khai được tích hợp với các công cụ phát triển phổ biến như Github, Bitbucket, AWS, Docker, và nhiều hơn nữa.

Với CircleCI, các nhà phát triển có thể tối ưu hóa quy trình phát triển phần mềm của họ, đảm bảo rằng mã nguồn mới được kiểm tra và tích hợp liên tục với mã nguồn hiện có, từ đó giảm thiểu lỗi và cải thiện chất lượng ứng dụng phần mềm.
#### Cách CircleCI hoạt động 
CircleCI được phục vụ dưới dạng SaaS và tại chỗ. CircleCI hướng tới nhiều môi trường và kiến trúc khác nhau như Linux, macOS, Windows, ARM và Android để đáp ứng nhu cầu của người dùng. CircleCI là một nền tảng liên tục tích hợp và triển khai phần mềm (CI/CD) tự động hóa quá trình xây dựng, kiểm thử và triển khai ứng dụng phần mềm. Giải pháp của họ là độc quyền và kết nối với nhiều dịch vụ khác để tiêu thụ các sản phẩm của họ.Ví dụ: chúng kết nối với một số dịch vụ Git để lắng nghe các sự kiện kích hoạt quy trình hoặc sử dụng mã nguồn được sử dụng để xây dựng và thử nghiệm. 
#### Tại sao nên sử dụng Circle CI
Ngày nay việc sử dụng CI/CD được sử dụng trong quy trình phát triển. Trong trường hợp ta chưa quen với nó, tích hợp liên tục là một phương pháp khuyến khích các nhà phát triển tích hợp mã của họ sớm và thường xuyên vào một kho lưu trữ dùng chung.

Quá trình tích hợp liên tục giúp đội phát triển phần mềm kiểm tra mã nguồn của họ trước khi hợp nhất. Tùy thuộc vào cấu hình được xác định, nó còn có thể dừng quá trình tích hợp nếu phát hiện bất kỳ lỗi nào. Thông tin này sẽ giúp đội nhận diện các vấn đề sớm và khắc phục chúng nhanh chóng, ngăn chặn các lỗi trong code. Nói cách khác, tích hợp liên tục cải thiện năng suất, hiệu quả và sự tự tin của đội, để ta có thể tìm ra vấn đề và giải quyết chúng nhanh chóng, để phát hành các sản phẩm chất lượng cao và ổn định hơn.
#### Những lợi ích khi ta sử dụng Circle CI
- Tăng năng suất và hiệu quả: Với tính năng tự động hóa quy trình phát triển, kiểm tra và triển khai, CircleCI giúp tăng năng suất và hiệu quả cho đội phát triển phần mềm, giảm thiểu thời gian và công sức để kiểm tra và phát triển ứng dụng.

- Cải thiện chất lượng sản phẩm: Bằng cách đảm bảo rằng mã nguồn được kiểm tra liên tục, CircleCI giúp cải thiện chất lượng sản phẩm và giảm thiểu số lượng lỗi.

- Đẩy nhanh quá trình phát triển: Tích hợp liên tục và triển khai liên tục giúp đội phát triển phần mềm đẩy nhanh quá trình phát triển và giảm thiểu thời gian để phát hành sản phẩm.

- Tích hợp dễ dàng: CircleCI tích hợp dễ dàng với các công cụ khác để kiểm tra mã nguồn, phát hiện lỗi và triển khai ứng dụng.

- Đảm bảo độ tin cậy: Bằng cách tự động hóa quy trình kiểm tra và triển khai, CircleCI giúp đảm bảo độ tin cậy của sản phẩm và giảm thiểu rủi ro xảy ra lỗi.
