### ISSUE TITLE
 Hoàn thành tìm hiểu về Docker và Docker Image

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#16]
Hoàn thành tìm hiểu về Circle CI và Docker

**Comment by mytranchi** [comment]
### Tìm hiểu Docker và Docker Image
#### Docker
Docker là một nền tảng ảo hóa mức container cho phép người dùng đóng gói, triển khai và quản lý các ứng dụng trong các container độc lập với các yêu cầu hệ thống. Điều này giúp cho việc triển khai ứng dụng trở nên dễ dàng và đồng nhất trên nhiều nền tảng khác nhau.
> Mức container (containerization) là một kỹ thuật ảo hóa cho phép đóng gói và chạy các ứng dụng và dịch vụ trong các môi trường độc lập gọi là container. Các container được tạo ra bằng cách đóng gói tất cả các thành phần cần thiết của một ứng dụng hoặc dịch vụ, bao gồm các thư viện, mã nguồn, cấu hình và các tài nguyên khác, vào bên trong một container độc lập với hệ thống máy chủ.

> Các container được tạo ra bằng cách sử dụng một lớp trừu tượng hóa ảo hóa máy chủ gọi là Docker engine hoặc các công nghệ containerization khác như LXC, CRI-O, rkt,.. Điều này cho phép các container chạy trên nhiều hệ điều hành và nền tảng khác nhau mà không cần phải lo lắng về sự khác biệt của các yêu cầu hệ thống.

> Mức container mang lại nhiều lợi ích, bao gồm tính di động, độc lập với hệ thống, độ tin cậy cao, khả năng mở rộng linh hoạt và hiệu suất tốt hơn so với các phương pháp ảo hóa truyền thống. Điều này giúp cho việc triển khai ứng dụng trở nên dễ dàng và đồng nhất trên nhiều nền tảng khác nhau và giúp tăng tốc quá trình phát triển và triển khai ứng dụng.

Các đặc điểm của Docker gồm:
- Đóng gói ứng dụng: Docker cho phép người dùng đóng gói các ứng dụng và các thành phần của chúng trong các container, đảm bảo tính di động và độc lập của chúng với môi trường hệ thống.
- Đồng nhất hóa môi trường: Docker cho phép người dùng đồng nhất hóa môi trường triển khai của các ứng dụng, đảm bảo tính ổn định và chính xác của môi trường triển khai.
- Linh hoạt và mở rộng: Docker cho phép người dùng dễ dàng triển khai các ứng dụng trên nhiều nền tảng khác nhau, từ máy tính cá nhân đến các hệ thống điện toán đám mây, và cung cấp khả năng mở rộng linh hoạt cho các ứng dụng.
- Hiệu suất và bảo mật: Docker cung cấp khả năng tách biệt tài nguyên giữa các container, giúp cải thiện hiệu suất và đảm bảo tính bảo mật của các ứng dụng.

Sử dụng Docker, ta có thể dễ dàng triển khai các ứng dụng trong các container, quản lý các container, kết nối các container với nhau và với các dịch vụ khác, và tạo các môi trường triển khai tùy chỉnh cho các ứng dụng của mình. Docker đã trở thành một công cụ quan trọng trong việc triển khai và quản lý các ứng dụng hiện đại.

#### Docker Image
Docker image là một file hoặc một tập hợp các file chứa tất cả các thành phần cần thiết để triển khai một ứng dụng trong một container Docker. Mỗi Docker image bao gồm một bản snapshot của các thành phần của ứng dụng, bao gồm các thư viện, mã nguồn, cấu hình và các tài nguyên khác. Docker image có thể được tạo ra từ một Dockerfile, một tập tin chứa các chỉ thị để thiết lập môi trường và cấu hình cho ứng dụng.

Mỗi Docker image có một tên duy nhất và phiên bản, được định nghĩa bởi Docker registry, nơi lưu trữ các Docker image trên toàn thế giới như Docker Hub, Amazon ECR, Google Container Registry, và nhiều hơn nữa. Người dùng có thể tìm kiếm và tải xuống các Docker image từ các registry này và sử dụng chúng để triển khai các container Docker.
> Trong Docker, registry là một dịch vụ lưu trữ các Docker images và cho phép người dùng tìm kiếm, tải xuống, tạo và chia sẻ các Docker images. Registry cũng là nơi để lưu trữ các images được tạo ra bởi người dùng và các images được chia sẻ công khai hoặc riêng tư.
> Docker có hai registry chính là Docker Hub được cung cấp bởi Docker và Docker Trusted Registry (DTR) được cung cấp bởi Docker Enterprise. Ngoài ra, còn có nhiều registry khác được cung cấp bởi các nhà cung cấp dịch vụ đám mây như Amazon EC2 Container Registry (ECR), Google Container Registry (GCR) và Microsoft Azure Container Registry (ACR).

Docker image có tính di động cao, cho phép người dùng triển khai các ứng dụng trên nhiều nền tảng khác nhau mà không cần phải lo lắng về sự khác biệt của các yêu cầu hệ thống. Người dùng cũng có thể tạo ra các Docker image tùy chỉnh của riêng mình và chia sẻ chúng thông qua các registry. Điều này giúp cho việc triển khai ứng dụng trở nên dễ dàng và đồng nhất trên nhiều nền tảng khác nhau và giúp tăng tốc quá trình phát triển và triển khai ứng dụng.

**Comment by tuanhcmute** [comment]
> ## Hoàn thành tìm hiểu về Docker và Docker Image

### 1. Docker là gì
- Docker là một nền tảng mã nguồn mở cho phép đóng gói, triển khai và chạy các ứng dụng trong các container. Docker giúp tạo ra một môi trường độc lập, có thể tái sử dụng và di động cho các ứng dụng, bao gồm cả các ứng dụng web, cơ sở dữ liệu và ứng dụng phân tán.

- Các container trong Docker là một đơn vị phần mềm độc lập, bao gồm tất cả những gì cần thiết để chạy ứng dụng, bao gồm cả mã nguồn, thư viện và các tài nguyên hệ thống. Các container này có thể chạy trên bất kỳ máy tính hoặc máy chủ nào mà đã được cài đặt Docker, mà không cần phải cấu hình lại hệ thống.

### 2. Lợi ích của docker
Docker có nhiều lợi ích so với các công nghệ khác, bao gồm:

- Tính di động: Docker cho phép đóng gói, triển khai và chạy các ứng dụng trong các container, tạo ra một môi trường độc lập, có thể tái sử dụng và di động cho các ứng dụng.

- Tính linh hoạt: Các container trong Docker có thể chạy trên bất kỳ máy tính hoặc máy chủ nào mà đã được cài đặt Docker, giảm thiểu sự phụ thuộc vào các yếu tố môi trường và tăng tính linh hoạt cho các ứng dụng.

- Tính nhất quán: Docker giúp đảm bảo tính nhất quán trong môi trường phát triển và triển khai, giúp đơn giản hóa việc xây dựng, kiểm tra và triển khai các ứng dụng.

- Tính đa nền tảng: Docker hỗ trợ nhiều nền tảng, bao gồm Linux, Windows và macOS, giúp đơn giản hóa việc triển khai các ứng dụng trên nhiều hệ thống khác nhau.

- Tính bảo mật: Docker cung cấp các tính năng bảo mật, bao gồm cơ chế phân quyền và kiểm soát truy cập, giúp đảm bảo an toàn cho các ứng dụng và dữ liệu.

- Tính tiết kiệm tài nguyên: Docker sử dụng các container để đóng gói các ứng dụng, giúp tiết kiệm tài nguyên hệ thống và tăng hiệu quả sử dụng máy chủ.

### 3. Docker image là gì?
- Docker image là một tập hợp các chỉ thị và cấu hình được đóng gói lại để tạo thành một bản sao của một hệ thống hoặc một ứng dụng. Docker image là một mẫu để tạo ra các container trong Docker, bao gồm cả các tài nguyên hệ thống như mã nguồn, thư viện, tập tin cấu hình và các tài nguyên khác.

- Một Docker image được tạo ra bằng cách sử dụng Dockerfile, một tệp văn bản chứa các chỉ thị và hướng dẫn để tạo ra một image. Sau khi Dockerfile được tạo, nó được sử dụng để tạo ra một Docker image bằng lệnh docker build.

- Docker image có tính chất không thay đổi và có thể sử dụng để tạo ra nhiều container, có thể chạy trên các máy tính hoặc máy chủ khác nhau. Khi một container được tạo ra từ một Docker image, container đó sẽ chứa tất cả các tài nguyên hệ thống cần thiết để chạy ứng dụng, bao gồm cả mã nguồn và các thư viện cần thiết.

### 4. Tạo một dockerfile đơn giản

- Chọn một hệ điều hành và phiên bản tương ứng để xây dựng Docker image. Ví dụ, bạn có thể chọn Ubuntu, CentOS, Debian, hoặc một phiên bản khác.

- Viết các chỉ thị và hướng dẫn trong Dockerfile để tạo ra một Docker image. Các chỉ thị này bao gồm các lệnh để cài đặt các phần mềm và thư viện cần thiết, sao chép các tệp cấu hình và mã nguồn vào image, và cấu hình các thiết lập môi trường.

- Lưu Dockerfile vào một thư mục trên máy tính.

- Sử dụng lệnh docker build để xây dựng Docker image từ Dockerfile. Lệnh này sẽ đọc Dockerfile và tạo ra một image tương ứng.

```
# Chọn hệ điều hành và phiên bản
FROM ubuntu:latest

# Cài đặt các gói phần mềm cần thiết
RUN apt-get update && \
    apt-get install -y apache2 php

# Sao chép tệp cấu hình vào image
COPY config.php /var/www/html/

# Thiết lập môi trường
ENV MY_VARIABLE=my_value

# Cấu hình lệnh mặc định khi container được chạy
CMD ["apache2ctl", "-D", "FOREGROUND"]
```

Trong ví dụ trên, Dockerfile sử dụng hệ điều hành Ubuntu và phiên bản mới nhất. Sau đó, nó cài đặt Apache và PHP, sao chép tệp cấu hình vào image, thiết lập biến môi trường và cấu hình lệnh mặc định khi container được chạy.

Sau khi lưu Dockerfile, chúng ta có thể sử dụng lệnh docker build để xây dựng Docker image từ Dockerfile này. Ví dụ: `docker build -t my-image .` (lưu ý dấu chấm ở cuối để chỉ định thư mục hiện tại là thư mục chứa Dockerfile).
