### ISSUE TITLE
 Hoàn thành tìm hiểu dữ liệu trả về từ API

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#18]
Ngày 6

**Comment by tuanhcmute** [comment]
> ## Hoàn thành tìm hiểu dữ liệu trả về từ API

- Sau khi đã được sự hướng dẫn của thầy nhóm đã hiểu thêm được một phần dữ liệu trả về
- Ta cùng xem xét lại dữ liệu được trả về:

```
{
  "ABCP231.031/HO": {
    "639bea5b095627cd88451540": {
      "angle_id": 2,
      "date": "2022-12-16T10:47:38.670000",
      "predict_result": [
        2.0,
        3.0,
        1.0,
        20.0,
        14.0
      ],
      "status": "ok"
    },
  "639bea5b095627cd88451540": {
      "angle_id": 2,
      "date": "2022-12-16T10:47:38.670000",
      "predict_result": [
        2.0,
        3.0,
        1.0,
        20.0,
        14.0
      ],
      "status": "ok"
    }
  },
  "ABCP231.032/HO": {
    "639bea5b095627cd88451540": {
      "angle_id": 2,
      "date": "2022-12-16T10:47:38.670000",
      "predict_result": [
        2.0,
        3.0,
        1.0,
        20.0,
        14.0
      ],
      "status": "ok"
    }
  }
}
```
- Dữ liệu trả về là một kết quả dự đoán của một vật thể gì đó.
- Mỗi vật thể đó sẽ được quan sát ở nhiều góc khác nhau, và mỗi góc sẽ có thời gian quan sát, kết quả dự đoán và cuối cùng sẽ là trạng thái cho biết có đúng là vật thể đó hay không 
- Chúng ta cũng có thể nhận ra rằng số lượng giá trị trong danh sách predict_result càng nhiều thì trạng thái sẽ đều là fail nhưng nếu số lượng giá trị trong danh sách predict_result càng ít thì ta chưa thể kết luận trạng thái vật thể ở góc này được

**Comment by mytranchi** [comment]
### Tìm hiểu về API trả về
Với API nhận được
```
{
"ABCP231.031/HO": {
"639bea5b095627cd88451540": {
"angle_id": 2,
"date": "2022-12-16T10:47:38.670000",
"predict_result": [2.0, 3.0, 1.0, 20.0, 14.0],
"status": "ok"
},
"639becb0095627cd88451564": {
"angle_id": 2,
"date": "2022-12-16T10:57:36.283000",
"predict_result": [2.0, 3.0, 1.0, 20.0, 14.0],
"status": "ok"
}..
"ABCP537.556/HO": {
"639be9aa095627cd8845153d": {
"angle_id": 2,
"date": "2022-12-16T10:44:42.244000",
"predict_result": [14.0, 1.0, 2.0, 20.0, 3.0],
"status": "ok"
},
"639bea18095627cd8845153e": {
"angle_id": 2,
"date": "2022-12-16T10:46:31.738000",
"predict_result": [2.0, 3.0, 1.9, 1.1, 20.0, 14.0],
"status": "fail"
}
```
 Sau khi tiếp nhận những gợi ý của thầy Phụng. Thì ta có thể hiểu về API này như sau
- Đây là API phản ánh tín hiệu sợi cáp quang. Có thể là ảnh chụp
- Trong một khoảng thời gian trong ngày ta sẽ nhận được dữ liệu từ các góc đo và một mảng các giá trị dự đoán và trạng thái tín hiệu ok hoặc fail
- Các giá trị trong predict_result có chức giá trị số thập phân thì status fail, các giá trị toàn là số nguyên thì status là ok
