### ISSUE TITLE
Tổng kết nội dung đã hoàn thành và các khó khăn gặp phải

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#19]
Ngày 7

**Comment by mytranchi** [comment]
### Tổng kết tuần vừa qua
Trong tuần rồi ta đã hoàn thành các công việc sau: 
#### Hoàn thành cấu hình CI/CD cho project
Tìm hiểu về CircleCI và Docker
Tìm hiểu cách cấu hình config.yml
Từ đó ta tìm hiểu về cách kết nối CircleCI với Docker Image cho project

#### Tìm hiểu về API
Thông qua sự trợ giúp của thầy Phụng. Nhóm em đã có thêm hiểu biết về API của Project này.

**Comment by tuanhcmute** [comment]
> ## Tổng kết những công việc trong tuần

### 1. Tổng kết những công việc trong tuần
**Trong tuần vừa qua nhóm đã làm những công việc sau:**
- [x] Tìm hiểu công cụ CircleCI và Docker.
- [x] Tìm hiểu cách cấu hình config.yml.
- [x] Tìm hiểu về cách kết nối CircleCI với Docker Image cho project cuối kì.
- [x] Tìm hiểu kỹ về API được cho

### 2. Những công việc đã hoàn thành
- Đã hoàn thành việc tìm hiểu cách hoạt động, sử dụng của công cụ CircleCI, Docker
- Đã biết cách cấu hình file config.yml để có thể chạy porject trên công cụ CircleCI sử dụng trên môi trường Docker
- Hiểu hơn được API đã cho

### 3. Những khó khăn còn gặp phải trong quá trình thực hiện
- Trong quá trình thực hiện các công việc trên nhóm có gặp phải một số khó khăn như, còn chưa hiểu nhiều về các lệnh trên docker dẫn tới khi thực hiện cấu hình chưa được đúng tiêu chuẩn.
- API ở nhiều chỗ vẫn còn nhiều khúc mắc chưa lời giải đáp.
