### ISSUE TITLE
Hoàn thành tìm 5 chức năng mới do nhóm đề xuất

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#21]

**Comment by tuanhcmute** [comment]
> ## Hoàn thành tìm 5 chức năng mới do nhóm đề xuất
**Sau khi đã thảo luận nhóm đã lựa chọn được 5 chức năng cho hệ thống bao gồm:**
- Đăng nhập hệ thống: Người dùng cần phải đăng nhập thì mới có thể sử dụng được các tính năng khác của hệ thống
- Đăng ký tài khoản: Người dùng cũng có thể tạo tài khoản để có thể sử dụng được hệ thống
- Quản lý người dùng: Quản lý tất cả người dùng hiện đang có trên hệ thống
- Quản lý thông tin cá nhân: Khi người dùng đăng nhập hoặc đăng ký sẽ có một trang cá nhân riên để có thể quản lý thông tin cá nhân của người dùng.
- Hiển thị biểu đồ: Hiển thị biểu đồ biểu diễn dữ liệu trả về từ API bên thứ 3

**Comment by mytranchi** [comment]
##### Chọn các chức năng cho Project
Thông qua quá trình thảo luận nhóm em đã chọn 5 chức năng như sau:
- Đăng nhập hệ thống (Login): Người dùng cần phải đăng nhập để sử dụng các tính năng của website
- Đăng ký (Register): Người dùng không có tài khoản đăng nhập có thể đăng ký tài khoản mới
- Quản lý người dùng (User Manager): Với user là admin ta có thể quản lý các user trong hệ thống
- Quản lý thông tin cá nhân (Profile Manager): Người dùng có thể xem và chỉnh sửa thông tin cá nhân của mình
- Hiển thị biểu đồ (Display Chart): Các biểu đồ sẽ được hiển thị trên biển đồ từ dữ liệu mà API trả về
