### ISSUE TITLE
Xác định các actor trong hệ thống, các Use Case trong hệ thống từ các chức năng đã đề xuất

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#22]
Thực hiện vẽ lược đồ usercase diagram

**Comment by tuanhcmute** [comment]
> ## Xác định các actor trong hệ thống, các Use Case trong hệ thống từ các chức năng đã đề xuất

1. Các actor trong hệ thống:
**Từ các chức năng mà nhóm đã đề xuất thì nhóm đã tìm được các actor có trong hệ thống như sau:**
- Những actor sử dụng hệ thống: Customer, admin 
- Những actor tương tác với hệ thống: API third party software.

2.   Các Use-Cases trong hệ thống
**Trong hệ thống sẽ có các use-case sau:**
- Customer sử dụng các chức năng: Login, register, profile manage, display chart.
- Admin sẽ có tất cả các chức năng của Customer và sẽ có thêm chức năng: User manage
- API third party software sẽ tương tác với chức năng hiển thị biểu đồ

**Comment by mytranchi** [comment]
> ### Xác định các actor và usecase trong hệ thống
##### Từ các chức năng đã chọn ta có 
##### 1. Các actor
- Admin, User
##### 2. Các UseCase
- Login
- Register
- Profile Manage
- Display Chart
- User Manage
