### ISSUE TITLE
 Xác định mối quan hệ giữa actor và use-cases

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#23]
Hoàn thành vẽ lược đồ usercase diagram

**Comment by mytranchi** [comment]
> #### Xác định mối quan hệ giữa Use Case và Actor
##### Sau khi đã các định được các Use Case và cá Actor ta tiến hành tạo mối quan hệ giữa chúng-
> Ta đã có các actor và usecase sau
- Actor: Admin, User
- UseCase: Login, Register, Profile Manage, User Manage, Display Chart
> Mối quan hệ giữa Actor và UseCase
- Với Actor User : actor này có thể sử dụng các usecase: Login, Register, Profile Manage, Display Chart
- Với Actor Admin: actor này có thể sử dụng các usecase: Login, User Manage, Profile Manage, Display Chart
> Mối quan hệ giữa các Use Case
- UseCase `Login` bao gồm (include) các UseCase Profile Manage, User Manage, Display Chart 
Tức là các UseCase trên chỉ được thực hiện khi UseCase Login được thực hiện thành công

**Comment by tuanhcmute** [comment]
> ## Xác định mối quan hệ giữa actor và use-cases

1. Ở task trước nhóm đã xác định được các Actor trong hệ Customer, admin và các use-case đó là login, register, profile manage, display chart, User manage.

2. Thực hiện xác định mối quan hệ giữa actor và các use-cases

- Customer sẽ tương tác với các use-case login, register, profile manage, display chart.

- Admin sẽ tương tác với use-case login, profile manage, display char, User manage.

- Các use-case như profile manage, display char, User manage đều phải include use-case Login. Nghĩa là các chức năng này chỉ có thể tương tác khi người dùng đã login vào hệ thống
