### ISSUE TITLE
Thực hiện vẽ lược đồ usercase

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#24]

**Comment by tuanhcmute** [comment]
> ## Thực hiện vẽ lược đồ use-cases

1. Từ những phân tích ở bài trước nhóm đã thực hiện vẽ usercase diargram như sau:

![usercase](https://github.com/tuanhcmute/Nhom1_CCPTPM/blob/main/docs/use-case.jpg?raw=true)  

2. Phân tích usercase

- Customer sẽ tương tác với các use-case login, register, profile manage, display chart.

- Admin sẽ tương tác với use-case login, profile manage, display char, User manage.

- Các use-case như profile manage, display char, User manage đều phải include use-case Login. Nghĩa là các chức năng này chỉ có thể tương tác khi người dùng đã login vào hệ thống

**Comment by mytranchi** [comment]
> Thực hiện vẽ UseCase Diagram

Từ việc tìm kiếm các Actor và UseCase ta tiến hành vẽ UseCase như sau

![UseCase Diagram](https://raw.githubusercontent.com/tuanhcmute/Nhom1_CCPTPM/main/docs/use-case.jpg)

Trong đó có các mối quan hệ giữa Actor và UseCase; mối quan hệ giữa các UseCase như đã trình bày ở task trước
