### ISSUE TITLE
Hoàn thành vẽ lược đồ class diagram

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#25]
Mô tả các lớp, thiết kế các đối tượng và quan hệ giữa các đối tượng đó

**Comment by tuanhcmute** [comment]
> ## Hoàn thành vẽ lược đồ class diagram #25

1. Từ những phân tích ở bài trước nhóm đã thực hiện vẽ usercase diargram như sau:

![ Class diagram](https://raw.githubusercontent.com/tuanhcmute/Nhom1_CCPTPM/main/docs/class-diagram.jpg)  

2. Phân tích Class diagram

- Sau khi phân tích từ lược đồ usercase thì nhóm đã làm được 2 class diagram: Gồm class Role và class User.

- Đối với class Role sẽ bao gồm những role của một User. Những role này sẽ quy định những gì user đó có quyền được làm và ta có thể thấy được mối liên kết giữa bảng role với user là một role có thể nhiều user.

- Đối với bảng user sẽ chứa những thông tin của user như họ tên, ngày tháng năm sinh, email, mật khẩu, một số trường để kiểm tra user đó đã được kích hoạt hay chưa. Và bảng user này sẽ có mỗi liên hệ với bảng Role đó là một user chỉ có một Role duy nhất.

**Comment by mytranchi** [comment]
> ### Vẽ lượt đồ Class Diagram 
1. Từ những thảo luận trước ta có thể thiết kế các class như sau:

![Class Diagram](https://raw.githubusercontent.com/tuanhcmute/Nhom1_CCPTPM/main/docs/class-diagram.jpg)

2. Giải thích chi thiết
- Class User dùng để lưu tài khoản và thông tin của user dùng để đăng nhập vào tài khoản
- Class Role dùng để phân quyền cho các user. Hạn chế quyền truy cập các user người dùng khác cũng quản lý các tác vụ liên quan khi cần thiết
