### ISSUE TITLE
Hoàn thành vẽ lược đồ activity diagram

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#26]
Mô tả các hoạt động và quy trình sử dụng các đối tượng đó.

**Comment by tuanhcmute** [comment]
> ## Hoàn thành vẽ lược đồ activity diagram #26

1. Lược đồ login, register activity

![Lược đồ login, register activity](https://raw.githubusercontent.com/tuanhcmute/Nhom1_CCPTPM/main/docs/login-register-activity.png)  

2. Lược đồ display chart activity

![Lược đồ display chart activity](https://raw.githubusercontent.com/tuanhcmute/Nhom1_CCPTPM/main/docs/displaychart-activity.png)

3. Lược đồ forgot password activity

![Lược đồ forgot password activity](https://raw.githubusercontent.com/tuanhcmute/Nhom1_CCPTPM/main/docs/forgot-password-activity.png)

4. Lược đồ profile manage activity

![Lược đồ profile manage activity](https://raw.githubusercontent.com/tuanhcmute/Nhom1_CCPTPM/main/docs/profile-manage-acitvity.png)  

5. Lược đồ user manage activity

![Lược đồ user manage activity](https://raw.githubusercontent.com/tuanhcmute/Nhom1_CCPTPM/main/docs/user-manage-activity.png)

**Comment by mytranchi** [comment]
> ## Vẽ các Activity  Diagram 

Các Acitivy Diagram được tham khảo từ nhóm 06 cùng đề tài cuối kỳ
1. Lược đồ login, register 
![login và register](https://raw.githubusercontent.com/tuanhcmute/Nhom1_CCPTPM/main/docs/login-register-activity.png)
2. Lược đồ forgot password
![forgot password](https://raw.githubusercontent.com/tuanhcmute/Nhom1_CCPTPM/main/docs/forgot-password-activity.png)
3. Lược đồ display chart
![display chart](https://raw.githubusercontent.com/tuanhcmute/Nhom1_CCPTPM/main/docs/displaychart-activity.png)
4. Lược đồ user manage
![user manage](https://raw.githubusercontent.com/tuanhcmute/Nhom1_CCPTPM/main/docs/user-manage-activity.png)
5. Lược đồ profile manage 
![user manage](https://raw.githubusercontent.com/tuanhcmute/Nhom1_CCPTPM/main/docs/profile-manage-acitvity.png)
