### ISSUE TITLE
Hoàn thành review các công việc trong tuần

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#27]

**Comment by tuanhcmute** [comment]
> ## Hoàn thành review các công việc trong tuần #27

1. Trong tuần nhóm đã thực hiện được các công việc sau:

- Hoàn thành việc lựa chọn chức năng cho đề tài

- Hoàn thành vẽ được lược đồ usercase dựa trên chức năng đã đưa ra

- Hoàn thành vẽ được lược đồ class diagram dựa theo usercase

- Hoàn thành vẽ được lược đồ activity cho các chức năng đã đề ra

2. Một số khó khăn mà nhóm đã gặp phải

- Đã hoàn thành và hiện tại chưa gặp phải khó khăn nào

**Comment by mytranchi** [comment]
> ## Review các công việc trong tuần
1. Các công việc đã thực hiện
- Lựa chọn 5 chức năng cho đề tài cuối kỳ
- Vẽ lược đồ usercase diagram
- Vẽ lược đồ class diagram
- Vẽ các lượt đồ activity diagram
2. Khó khăn
- Hiện tại chưa gặp phải khó khăn nào
