### ISSUE TITLE
Hoàn thành tạo repository trên github

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#3]

**Comment by tuanhcmute** [comment]
- Thực hiện tạo account github với email sinh viên
- Tạo một repository trên github

**Comment by mytranchi** [comment]
Đã hoàn thành

**Comment by mytranchi** [comment]
Đã tạo user github với tài khoản sinh viên 
Đã tham gia vào reponsitory

**Comment by tuanhcmute** [comment]
- Các thành viên đã hoàn thành việc tạo account github với mail sinh viên.
- Thực hiện tạo một repository để tiến hành làm project cuối kì, hoàn thành tạo Milestone, issue, tạo task cho các thành viên trong team.
