### ISSUE TITLE
Hoàn thành thực hiện thêm giao diện đăng ký tài khoản

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#30]

**Comment by tuanhcmute** [comment]
> ## Hoàn thành thực hiện thêm giao diện đăng ký tài khoản #30

1. Hình ảnh giao diện đăng ký tài khoản

![Giao diện sign up](https://github.com/tuanhcmute/Nhom1_CCPTPM/blob/main/docs/signup.jpg?raw=true)

**Comment by mytranchi** [comment]
> #### Hoàn thành giao diện trang SignUp
- Trang Signup cũng tương tự như trang Login. Nhóm em sử dụng Jinja2, kết hợp với Form có nhiều thông tin hơn để lưu dữ liệu cá nhân của người dùng
![SignUp](https://raw.githubusercontent.com/tuanhcmute/Nhom1_CCPTPM/main/docs/signup.jpg)
