### ISSUE TITLE
Hoàn thành thực hiện lựa chọn biểu đồ để biểu diễn

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#33]

**Comment by tuanhcmute** [comment]
> ## Hoàn thành thực hiện lựa chọn biểu đồ để biểu diễn #33
> 

1. Sau khi đã thảo luận nhóm đã lựa chọn được một số lược đồ để biểu diễn như sau:

- Biểu đồ cột.
![Giao diện sign up](https://github.com/tuanhcmute/Nhom1_CCPTPM/blob/main/docs/barchart.jpg?raw=true)  

- Biểu đồ line.
![Giao diện sign up](https://github.com/tuanhcmute/Nhom1_CCPTPM/blob/main/docs/linechart.jpg?raw=true)  

- Biểu đồ Multi Axis Line
![Giao diện sign up](https://github.com/tuanhcmute/Nhom1_CCPTPM/blob/main/docs/mutiplelinechart.jpg?raw=true)  

- Biểu đồ tròn
![Giao diện sign up](https://github.com/tuanhcmute/Nhom1_CCPTPM/blob/main/docs/piechart.jpg?raw=true)

**Comment by mytranchi** [comment]
> ### Lựa chọn các biểu đồ
- Sau khi thảo luận nhóm em chọn một số loại biểu đồ sau

  +Biểu đồ cột ghép (Stacked Column Chart): là loại biểu đồ thể hiện dữ liệu bằng các cột được ghép lại với nhau. Mỗi cột đại diện cho một nhóm dữ liệu, và các giá trị của các nhóm được ngăn cách bằng các đường kẻ ngang. Biểu đồ cột ghép thường được sử dụng để so sánh tổng giá trị của các nhóm.

  +Biểu đồ tròn (Pie Chart): là loại biểu đồ thể hiện dữ liệu dưới dạng phần trăm. Biểu đồ tròn được chia thành các phần tương ứng với phần trăm của giá trị của từng nhóm dữ liệu. Biểu đồ tròn thường được sử dụng để so sánh tỉ lệ các nhóm dữ liệu trong tổng thể.

  +Biểu đồ đường (Line Chart): là loại biểu đồ thể hiện xu hướng hoặc sự thay đổi của dữ liệu theo thời gian. Biểu đồ đường được vẽ bằng cách kết nối các điểm dữ liệu bằng các đường thẳng. Biểu đồ đường thường được sử dụng để theo dõi xu hướng của các dữ liệu trong một khoảng thời gian nhất định.

  +Biểu đồ cột (Column Chart): là loại biểu đồ thể hiện dữ liệu bằng các cột đứng. Mỗi cột đại diện cho một nhóm dữ liệu, và chiều cao của cột thể hiện giá trị của nhóm đó. Biểu đồ cột thường được sử dụng để so sánh giá trị của các nhóm dữ liệu.
