### ISSUE TITLE
Hoàn thành review các công việc đã thực hiện trong tuần

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#35]

**Comment by tuanhcmute** [comment]
> ## Hoàn thành review các công việc đã thực hiện trong tuần #35
>

1.   Hoàn thành thực hiện chỉnh sửa database

2. Hoàn thành thực hiện thêm giao diện đăng ký tài khoản

3. Hoàn thành thực hiện chức năng đăng ký tài khoản

4. Hoàn thành thực hiện chỉnh sửa chức năng đăng nhập

5. Hoàn thành thực hiện lựa chọn biểu đồ để biểu diễn

6. Hoàn thành thực hiện chức năng biểu đồ biểu diễn dữ liệu

**Comment by mytranchi** [comment]
> ### Reivew các công việc trong tuần
- Trong tuần qua nhóm em đã hoàn thành các công việc sau:
+Hoàn thành chỉnh sửa database
+Tạo trang signup và code chức năng signup
+Chỉnh sửa lại chức năng login: thêm một số thuộc tính và check dữ liệu đầu vào
+Chọn một số dạng biểu đồ và thực hiện vẽ biểu đồ từ data trả về
