### ISSUE TITLE
Hoàn thành tìm hiểu về token

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#4]
- Token là gì?
- Cách  sử dụng token?
- Mô tả token sử dụng trong dự án?

**Comment by mytranchi** [comment]
Tìm hiểu về token
1. Token là một dạng chữ ký số hay chữ ký điện tử được mã hóa thành những con số trên thiết bị chuyên biệt. Mã Token tạo ra là dạng mã OTP nghĩa là mã sử dụng được một lần và tạo ngẫu nhiên cho mỗi giao dịch.
2. Cách sử dụng token phụ thuộc vào mục đích sử dụng của nó. Tuy nhiên, một số cách sử dụng token phổ biến bao gồm:
- Xác thực người dùng: Token có thể được sử dụng để xác thực người dùng trong các ứng dụng trực tuyến. Người dùng cần phải nhập mã token để xác nhận danh tính của họ và truy cập vào ứng dụng.
- Giao dịch tiền điện tử: Token có thể được sử dụng để thực hiện các giao dịch trên các nền tảng blockchain. Người dùng có thể mua, bán hoặc trao đổi các loại token khác nhau trên các sàn giao dịch tiền điện tử.
- Tài trợ dự án: Các dự án mới có thể sử dụng token để tài trợ cho mình thông qua ICO (Initial Coin Offering). Những người đầu tư sẽ mua token của dự án với giá trị tiền tệ hoặc tiền điện tử khác để đổi lấy các quyền lợi, tài sản hoặc dịch vụ của dự án.
- Truy cập dịch vụ: Token cũng có thể được sử dụng để truy cập vào các dịch vụ trực tuyến khác nhau, như hệ thống thanh toán hoặc mạng xã hội. Người dùng cần phải sử dụng token để truy cập vào các tính năng hoặc dịch vụ đặc biệt của nền tảng đó.

Tùy thuộc vào mục đích sử dụng, token có thể được sử dụng như một đơn vị giá trị, mã xác thực, hoặc đại diện cho các quyền lợi hoặc tài sản khác nhau.
3. Tìm hiểu token của project
Trong token trả về gồm có các thông tin sau
{"access_token":"Dbgq2fHK9ICl97pjnMzHXQCcjGM2Dnyy","expires_in":7200,"token_type":"bearer"}
Trong đó
"access_token": là mã truy cập (access token), đại diện cho quyền truy cập vào tài nguyên được bảo vệ của người dùng sau khi xác thực thành công. Mã truy cập này sẽ được sử dụng để truy cập các tài nguyên được bảo vệ khác trên API. Trong token trên giá trị của access_token là "Dbgq2fHK9ICl97pjnMzHXQCcjGM2Dnyy".

"expires_in": là thời gian số giây còn lại trước khi mã truy cập hết hạn. Trong token trên giá trị của expires_in là 7200 giây (tương đương với 2 giờ).

"token_type": xác định loại mã truy cập trả về. Trong token trên loại mã truy cập là "bearer".

Các thông tin trên cung cấp cho người dùng thông tin cần thiết để sử dụng mã truy cập và truy cập các tài nguyên được bảo vệ trên API trong khoảng thời gian cho phép.

**Comment by tuanhcmute** [comment]
>### 1. Tìm hiểu về token
> - Token là Chữ ký số hoặc chữ ký điện tử là tên gọi khác của token theo đó chúng được mã hóa thành những con số trên thiết bị chuyên biệt. Mã Token tạo ra là dạng mã OTP có nghĩa là mã sử dụng được một lần và tạo ngẫu nhiên cho mỗi giao dịch.
> - Hiện nay có rất nhiều doanh nghiệp áp dụng token cho những giao dịch của mình, đặc biệt là những giao dịch Online. Nếu nói một cách dễ hiểu thì Token được xem như một mật khẩu đặc biệt phải nhập trong mỗi lần giao dịch nhằm mục đích bảo mật thông tin.

> ### 2. Cách sử dụng token?
> Cách sử dụng token phụ thuộc vào mục đích sử dụng của nó. Và có một số cách để sử dụng token:
> + Sử dụng trong các dịch vụ web service
> + Giao dịch tiền điện tử
> + Xác thực người dùng

> ### 3. Token trong project
> - Client app muốn sử dụng service thì bắt buộc phải sử dụng api để get Token. 
> - User client muốn access tới endpoints nào đó bắt buộc phải gửi kèm token này ở mỗi request để xác thực:
Nếu gửi thành công token sẽ có dạng như bên dưới
{"access_token":"Dbgq2fHK9ICl97pjnMzHXQCcjGM2Dnyy","expires_in":7200,"token_type":"bearer"}
> Trong đó:
> "access_token": Được sử dụng để truy cập các tài nguyên trên API. 
> "expires_in": là thời gian số giây còn lại trước khi mã truy cập hết hạn. 
> "token_type": xác định loại mã truy cập trả về. Trong token trên loại mã truy cập là "bearer".
