### ISSUE TITLE
Hoàn thành tìm hiểu dịch vụ EC2 của AWS

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#46]

**Comment by tuanhcmute** [comment]
> ## Tìm hiểu dịch vụ EC2 của AWS

Dịch vụ EC2 (Elastic Compute Cloud) của AWS là một dịch vụ máy chủ ảo (virtual server) trên đám mây với khả năng mở rộng linh hoạt và tính linh động cao. EC2 cho phép người dùng thuê các máy chủ ảo để chạy các ứng dụng của mình trên đám mây AWS một cách dễ dàng và nhanh chóng.

Một số đặc điểm của EC2:

- Khả năng mở rộng linh hoạt: Người dùng có thể tăng hoặc giảm số lượng máy chủ ảo một cách nhanh chóng để đáp ứng nhu cầu của ứng dụng.
- Tính linh động cao: Người dùng có thể tùy chỉnh các tài nguyên của máy chủ ảo như bộ nhớ RAM, dung lượng đĩa, CPU và nhiều hơn nữa.
- Tiết kiệm chi phí: Người dùng chỉ phải trả tiền cho các tài nguyên mà họ sử dụng thực sự, giảm thiểu chi phí đầu tư ban đầu cho phần cứng máy chủ thực.
- Hỗ trợ nhiều hệ điều hành: EC2 hỗ trợ nhiều hệ điều hành như Windows, Linux, Unix và nhiều hơn nữa.
- Tính khả dụng cao: EC2 cung cấp các tính năng như tự động khôi phục, sao lưu và phục hồi để đảm bảo dịch vụ luôn sẵn sàng.

Để sử dụng EC2, người dùng cần tạo một instance (một máy chủ ảo) và cấu hình nó để chạy các ứng dụng của mình. EC2 cũng cung cấp các tính năng giám sát và quản lý để người dùng có thể theo dõi trạng thái của các instance và tối ưu hóa hiệu suất của chúng.

Qua đó, EC2 là một trong những dịch vụ cơ bản của AWS, được sử dụng rộng rãi trong các ứng dụng web, ứng dụng di động và các dịch vụ công nghệ khác.

**Comment by mytranchi** [comment]
#### Tìm hiểu về EC2 của AWS
Amazon Elastic Compute Cloud (EC2) là một dịch vụ đám mây được cung cấp bởi AWS, cung cấp khả năng lưu trữ và tính toán đám mây. EC2 cho phép người dùng thuê các máy ảo (instances) trên nền tảng đám mây của Amazon, giúp tăng tính linh hoạt và hiệu quả trong việc triển khai và quản lý các ứng dụng.

EC2 cung cấp một loạt các lựa chọn cho loại máy ảo, bao gồm các máy ảo tối ưu cho các ứng dụng web, cơ sở dữ liệu, và tính toán khoa học. Mỗi máy ảo đều có các thông số cấu hình khác nhau, bao gồm số lượng bộ xử lý, bộ nhớ và dung lượng lưu trữ. Người dùng cũng có thể tùy chỉnh các máy ảo của họ bằng cách cài đặt phần mềm và thực hiện các cấu hình khác phù hợp với nhu cầu của họ.

EC2 cung cấp các tính năng và công cụ để quản lý các máy ảo của người dùng, bao gồm Amazon Elastic Block Store (EBS) để lưu trữ dữ liệu, Amazon Elastic Load Balancer (ELB) để phân phối tải, và Amazon Virtual Private Cloud (VPC) để tạo mạng riêng ảo. EC2 cũng cung cấp tính năng tự động hóa để tự động tăng hoặc giảm số lượng các máy ảo dựa trên nhu cầu thực tế của ứng dụng, giúp tối ưu hóa hiệu suất và chi phí.

Tóm tắt lại thì EC2 là một dịch vụ đám mây cung cấp khả năng lưu trữ và tính toán đám mây. EC2 cho phép người dùng thuê các máy ảo trên nền tảng đám mây của Amazon, cung cấp tính linh hoạt và hiệu quả trong việc triển khai và quản lý các ứng dụng. EC2 cung cấp các tính năng và công cụ để quản lý các máy ảo của người dùng, và có tính năng tự động hóa để tối ưu hóa hiệu suất và chi phí của người dùng.
