### ISSUE TITLE
Tổng kết các công việc đã làm trong tuần

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#47]

**Comment by tuanhcmute** [comment]
> ## Tổng kết các công việc đã làm trong tuần 

1. Hoàn thành tìm hiểu về virtualization vs containerization
2. Hoàn thành tìm hiểu về docker 
3. Hoàn thành tìm hiểu về Dockerfile và Docker Compose
4. Hoàn thành cấu hình Dockerfile và docker-compose.yml cho project
5. Hoàn thành tìm hiểu AWS
6. Tìm hiểu dịch vụ EC2 của AWS
7. Tổng kết các công việc đã làm trong tuần

**Comment by mytranchi** [comment]
#### Tổng kết cac công việc đã thực hiện được trong tuần
- Hoàn thành tìm hiểu về virtualization vs containerization
- Hoàn thành tìm hiểu về docker
- Hoàn thành tìm hiểu về Dockerfile và Docker Compose
- Hoàn thành cấu hình Dockerfile và docker-compose.yml cho project
- Hoàn thành tìm hiểu AWS
- Tìm hiểu dịch vụ EC2 của AWS
