### ISSUE TITLE
Hoàn thành tìm hiểu về source code đề tài

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#5]

**Comment by tuanhcmute** [comment]
## Source code cho sẵn gồm 2 file getToken và getData đươc viết bằng ngôn ngữ python.
> ### 1. Đầu tiên với file getToken.py
- File này sẽ cho phép chúng ta lấy token từ API bên thứ 3. Để có thể lấy được token thì chúng ta cần phải có 2 thư viện 1 là request và thư viện json.
- Với thư viện requests thì giúp chúng ta làm sẽ giúp chúng ta lấy được token từ API bên thứ 3. Chúng ta sẽ cung cấp một số thông tin như endpoint, một số thông tin header, payload gồm 2 thông tin là clientId và clientServer. và payload sẽ được thư viện json dumps ra và gửi theo request.
- Server sẽ xử lý và trả về phản hổi. Phản hổi nãy sẽ nằm trong biến response. Và để lấy được thông tin như access_token, expires_in, token_type thì ta cần truy cập tới thuộc tính text của biến response.

> ### 2. File getData.py
- Trong file này cũng sử dụng hai thư viện request và json để thực hiện lấy data.
- Để lấy được data thì cần phải có được một endpoint tới resource đó và access_token. Sau khi đã lấy được access_token thì chúng ta thực hiện lấy mã token đó đỏ vào phần Authorization của header. Và dùng thư viện request để gửi yêu cầu này lên server. 
- Server sẽ xử lý check access_token còn hiệu lực hay không. Nếu còn thì tiến hành trả ra kết quả về cho ngưởi dùng. Còn ngược lại thực hiện trả về cho người dùng một data thông báo người dùng access_token invalid.
- Nếu lấy được data thì data sẽ có dạng như sau:
{"ABCP231.031/HO": {"639bea5b095627cd88451540": {"angle_id": "", "date": "", "predict_result": [], "status": }}}
- "ABCP231.031/HO": Là một trường khóa đại diện cho tên của một đối tượng được xác định trong API
- 639beceb095627cd8845156d": Các khóa này là các ID đại diện cho các mẫu dữ liệu được lưu trữ trong hệ thống.
- "angle_id": Là một trường mô tả góc nhìn được sử dụng trong quá trình phân tích.
- "date": Là một trường mô tả thời gian mẫu dữ liệu được lưu trữ trong hệ thống.
- "predict_result": Là một trường mô tả kết quả dự đoán. Trong trường hợp này, kết quả dự đoán là một mảng chứa 5 giá trị
- "status": Là một trường mô tả trạng thái của mẫu dữ liệu. Có 2 trạng thái là "ok" và "falt"

**Comment by mytranchi** [comment]
# Tìm hiểu về soucre code đề tài
### Trong đề tài ta đã có 2 file python bao gồm: getToken.py và getData.py. Chi tiết như sau:
#### **getToken.py**
- Trong đoạn code này có sử dụng thư viện requests để thực hiện một yêu cầu HTTP POST đến một API endpoint tại địa chỉ 
*https://cads-api.fpt.vn/fiber-detection/v2/getToken*
Yêu cầu POST này chứa một payload dưới dạng chuỗi JSON được định dạng bằng json.dumps() trong Python. Payload này chứa hai thông tin là clientId và clientSecret được cung cấp bởi người dùng.
- Header của yêu cầu POST được thiết lập để cho server biết rằng payload được gửi đi là dạng JSON.
- Sau đó, requests.request() được gọi với hai tham số là "POST" để chỉ định phương thức của yêu cầu, và địa chỉ của API endpoint. requests cũng được truyền payload và header trong các tham số tương ứng.
- Sau khi yêu cầu được gửi, server sẽ xử lý payload và trả về một phản hồi. Phản hồi này được lưu trong biến response. Lúc này ta sẽ nhận được một chuỗi JSON có ba trường access_token, expires_in, và token_type:
access_token: Chứa một mã token được cấp cho người dùng. Mã token này có thể được sử dụng để xác thực cho các yêu cầu truy cập vào các API endpoint khác của ứng dụng.
expires_in: Chứa số giây còn lại cho đến khi mã token hết hạn. Trong trường hợp này, mã token sẽ hết hạn sau 7200 giây (hoặc 2 giờ) kể từ khi nó được cấp.
token_type: Chứa loại mã token được cấp cho người dùng. Trong trường hợp này, loại token là "bearer", đây là một trong những loại phổ biến trong việc xác thực cho các ứng dụng web.

#### **getData.py**
- Đoạn code sử dụng thư viện requests để thực hiện một yêu cầu HTTP POST đến một API endpoint tại địa chỉ
*http://cads-api.fpt.vn/fiber-detection/v2/using_json_inf/2022/12*
Yêu cầu POST này không chứa payload nào, nên biến payload được gán với một chuỗi rỗng.
- Header của yêu cầu POST bao gồm hai phần:
Content-Type: Thiết lập cho server biết rằng payload của yêu cầu là dạng JSON.
Authorization: Chứa một mã token với token được tạo ra từ file getToken.py và thời gian có hiệu lực là 2 giờ . Đây là mã token được cung cấp cho người dùng để xác thực việc truy cập vào API endpoint.
- Sau đó, requests.request() được gọi với hai tham số là "POST" để chỉ định phương thức của yêu cầu, và địa chỉ của API endpoint. requests cũng được truyền payload và header trong các tham số tương ứng.
- Sau khi yêu cầu được gửi, server sẽ xử lý payload và trả về một phản hồi. Ta nhận được một tập các dữ liệu gồm các trường:
 "ABCP231.031/HO": Là một trường khóa đại diện cho tên của một đối tượng được xác định trong API. Tên này là "ABCP231.031/HO".
"639bea5b095627cd88451540", "639becb0095627cd88451564", "639beceb095627cd8845156d": Các khóa này là các ID đại diện cho các mẫu dữ liệu được lưu trữ trong hệ thống. Các ID này được đặt tự động bởi hệ thống và không có nghĩa đặc biệt.
"angle_id": Là một trường mô tả góc nhìn được sử dụng trong quá trình phân tích.
"date": Là một trường mô tả thời gian mẫu dữ liệu được lưu trữ trong hệ thống.
"predict_result": Là một trường mô tả kết quả dự đoán. Trong trường hợp này, kết quả dự đoán là một mảng chứa 5 giá trị
"status": Là một trường mô tả trạng thái của mẫu dữ liệu. Có 2 trạng thái là "ok" và "falt"
