### ISSUE TITLE
Hoàn thành tìm hiểu đề tài

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#6]

**Comment by tuanhcmute** [comment]
## Sau nhiều ngày tìm hiểu về đề tài. Sau đây sẽ là những tổng kết lại của project
> ### 1. Những nội dung đã hiểu
- Project thực hiện việc tạo một dashboard phân tích những dữ liệu được trả về thông qua một API bên thứ 3
- Để lấy được dữ liệu thì cần phải có token để khi lên server sẽ thực hiện phân tích xem người gửi yêu cầu có quyền để lấy dữ liệu về không.
- Token sẽ được giới hạn thời gian nên. Sau khi thời gian đã hết hạn thì cần phải refresh lại token để tiếp tục lấy dữ liệu khi cần thiết.
>
> ### 2. Một số nội dung còn chưa rõ
- Chưa rõ API trả dữ liệu dữ liệu thuộc vấn đề gì nên chưa thể phân tích dữ liệu sâu hơn?
- Cần phải thiết kế bao nhiêu chart về dữ liệu này để có thể phân tích dự đoán.

**Comment by mytranchi** [comment]
## Tổng kết sau khi tìm hiểu đề tài

### Những thông tin nhận được bao gồm
- Nhiệm vụ tạo một DashBoard phân tích các dữ liệu trên
- Trong project có sử dụng 2 file python gồm getToken.py và getData.py. Trong mỗi file lại có 1 API.
Với file getToken.py API cung cấp cho ta 1 token với thời gian có hiệu lực là 2 giờ
Với file getData.py API cần xác thực token có hiệu lực để xuất ra một tập data.
- Sau khi tìm hiểu thì ta nhận thấy Data có thể liên quan đến việc phân tích và dự đoán các kết quả về góc nghiêng của các đường sợi quang trên một thiết bị hoặc khu vực mạng nào đó bao gồm các thông số như ID, status, góc quay,...
### Một số nội dung còn gặp khó khăn
- Từ API trên chưa tìm ra được giải pháp khai thác dữ liệu sao cho hợp lý 
- Các thông tin nên hiển thị trên DashBoard và cách hiển thị sao cho  phù hợp
