### ISSUE TITLE
Hoàn thành lựa chọn công nghệ cho front-end

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#7]

**Comment by mytranchi** [comment]
### Sau khi bàn bạc và thảo luận. Nhóm em tiến hành chọn những công nghệ sau
##### Back-End
- Nhóm em sử dụng Framework Flask của Python. Bởi vì
>Flask là một framework nhỏ gọn và dễ tiếp cận, do đó rất thích hợp cho các ứng dụng web nhỏ hoặc trung bình.
Flask cung cấp một cấu trúc ứng dụng đơn giản và tùy chỉnh cho phép bạn thiết kế ứng dụng theo cách của riêng mình.
Flask hỗ trợ rất tốt cho các thư viện bên thứ ba, như SQLAlchemy, WTForms và Jinja2.
Flask cho phép các ứng dụng web RESTful với dễ dàng thông qua Flask-RESTful.
Flask cung cấp rất nhiều tài liệu, ví dụ như trang chủ Flask, các cuốn sách và các tài liệu khác giúp người dùng có thể nhanh chóng học và phát triển các ứng dụng web.
Flask là một framework web đáng tin cậy và được sử dụng rộng rãi trong cộng đồng Python 
##### Front-End
- Nhóm em sử dụng engine jinja2. Bởi vì 
>Cú pháp đơn giản và dễ hiểu
Có thể tái sử dụng: Jinja2 cho phép ta sử dụng các mẫu trong các tệp khác nhau và các ứng dụng khác nhau, giúp ta tối ưu hóa quá trình phát triển và tái sử dụng mã.
Hỗ trợ kế thừa mẫu (template inheritance): Jinja2 cung cấp tính năng kế thừa mẫu cho phép ta xây dựng các mẫu lớn hơn và phân chia chúng thành các khối nhỏ hơn để tái sử dụng.
##### Testing
- Nhóm em sử dụng pytest. Bời vì
>Dễ sử dụng và tiện lợi: Pytest cho phép bạn viết các bài kiểm tra (test) với cấu trúc đơn giản và dễ hiểu. Nó cũng cung cấp nhiều tính năng hữu ích như tạo báo cáo test, chạy các test case cụ thể và tạo coverage report.
Không cần sử dụng class: Với Pytest, ta không cần phải tạo các class để thực hiện kiểm tra, điều này giúp cho code trở nên gọn gàng và dễ hiểu hơn.
Tích hợp với các công cụ và thư viện khác: Pytest có khả năng tích hợp với các thư viện khác như Django, Flask, Selenium, hay các thư viện mocking, giúp cho việc kiểm thử trở nên linh hoạt và hiệu quả hơn.
Hỗ trợ các tính năng kiểm thử nâng cao: Pytest có khả năng kiểm thử nâng cao như parameterized testing, fixtures, xử lý lỗi tốt hơn, mock object, ... giúp cho kiểm thử trở nên dễ dàng và chính xác hơn.
##### CSDL
- Nhóm em sử dụng PostgresQL. Bởi vì
>Kiểu dữ liệu đa dạng: PostgreSQL cung cấp nhiều kiểu dữ liệu như nguyên hàm (các nguyên số, boolean, số, chuỗi), cấu trúc (UUID, Range, Array, Date/time), hình học, tùy chỉnh và document.
Toàn vẹn dữ liệu: Dữ liệu trong PostgreSQL được đảm bảo tính toàn vẹn nhờ vào các khóa như Primary Keys, Foreign Keys, UNIQUE, NOT NULL, Khóa hàm số/ Explicit Locks, Khóa khuyến nghị/ Advisory Locks, …
Các thiết lập nâng cao: PostgreSQL cung cấp tính năng lập danh mục nâng cao, trình lập kế hoạch, trình tối ưu các truy cập phức tạp, thống kê số liệu trên nhiều cột, quét index – only, giao tác dạng test, điều khiển đồng thời nhiều phiên bản, phân vùng bảng, truy vấn đọc song song, độ tin cậy, phục hồi sau sự cố, nhật ký ghi trước (Write-ahead Logging – WAL),…
Chức năng bảo mật: PostgreSQL hỗ trợ xây dựng hàng rào bảo mật, xác thực mạnh mẽ như SCRAM-SHA-256, SSPI, LDAP, GSSAPI, Certificate,…
##### Automation testing
- Nhóm em sử dụng Circle CI. Bởi vì CI dễ sử dụng, cung cấp nhiều tính năng đồng thời tích hợp nhiều công cụ khác nhau.
