### ISSUE TITLE
Hoàn thành set-up code

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#8]

**Comment by mytranchi** [comment]
## SET UP CODE
> #### Nhóm em đã tiến hành set up code python sử dụng framework Flask. Cấu trúc thư mục như sau:  

Nhom1_CCPTPM
│   .env
│   .gitignore
│   README.md
│   requirements.txt
│   
├───.circleci
│       config.yml
│       
├───.github
│       FUNDING.yml
│       
├───app
│   │   app.py
│   │   config.py
│   │   extensions.py
│   │   __init__.py
│   │   
│   ├───authen
│   │       routes.py
│   │       __init__.py
│   │       
│   ├───main
│   │       routes.py
│   │       __init__.py
│   │       
│   ├───model
│   │       user.py
│   │       
│   ├───static
│   │   ├───css
│   │   ├───fonts      
│   │   ├───images           
│   │   ├───js      
│   │   └───vendor
│   │               
│   ├───templates
│   │   │   base.html
│   │   │   data.html
│   │   │   index.html
│   │   │   login.html
│   │   │   
│   │   └───partials
│   │           footer.html
│   │           header.html
│   │           sidebar-nav.html
│   │           
│   ├───utils
│   │       contants.py
│   │       
│   └───vendor
│           getData.py
│           getToken.py
│           
└───tests
    │   conftest.py
    │   __init__.py
    │   
    ├───auth
    │       test_login.py
    │       
    └───main
            test_main.py
            

Trong đó:
- Thư mục .circleci: Thư mục chứa tệp tin cấu hình cho việc tích hợp liên tục bằng CircleCI.config.yml: Tệp tin cấu hình cho CircleCI.
- Thư mục .github: Thư mục chứa các tệp tin liên quan đến cấu hình của GitHub. FUNDING.yml: Tệp tin liệt kê các địa chỉ tài trợ cho dự án.
Trong thự mục app có:
    > Thư mục authen: Chứa các tệp tin liên quan đến chức năng đăng nhập, bao gồm tệp routes.py để định nghĩa các tuyến đường và xử lý yêu cầu của người dùng liên quan đến đăng nhập.

    > Thư mục main: Chứa các tệp tin liên quan đến chức năng chính của ứng dụng web, bao gồm tệp routes.py để định nghĩa các tuyến đường và xử lý yêu cầu của người dùng liên quan đến chức năng chính.

    > Thư mục model: Chứa các tệp tin liên quan đến định nghĩa và xử lý dữ liệu cho ứng dụng web, bao gồm tệp user.py để định nghĩa lớp User để lưu trữ thông tin người dùng.

    > Thư mục static: Chứa các tệp tin tĩnh như CSS, JavaScript, hình ảnh và phông chữ được sử dụng trong giao diện người dùng của ứng dụng web.

    > Thư mục templates: Chứa các tệp tin mẫu HTML được sử dụng để hiển thị giao diện người dùng của ứng dụng web, bao gồm các tệp mẫu cơ bản như base.html, index.html và login.html cùng với các tệp mẫu phần nhỏ khác được đặt trong thư mục partials.

    > Thư mục utils: Chứa các tệp tin hỗ trợ để xử lý các tác vụ như định nghĩa hằng số.

    > Thư mục vendor: Chứa các tệp getToken.py và getData.py mà dự án cung cấp

    > Thư mục tests chứa các tệp liên quan đến việc kiểm thử chức năng của ứng dụng. Trong thư mục tests có: 
    > Tệp conftest.py: Tệp cấu hình sẽ được sử dụng cho toàn bộ các bài kiểm tra trong thư mục này.
    > Thư mục auth: Chứa các tệp liên quan đến việc kiểm thử tính năng xác thực người dùng của ứng dụng.
    >Thư mục main: Chứa các tệp liên quan đến việc kiểm thử các tính năng chính của ứng dụng.

- Tệp .env: Chứa các biến môi trường được sử dụng trong ứng dụng web.
- Tệp app.py: Điểm khởi đầu của ứng dụng web, định nghĩa và cấu hình ứng dụng Flask.
- Tệp config.py: Chứa các cấu hình chung cho ứng dụng web, như cấu hình cơ sở dữ liệu và cấu hình gửi email.
- Tệp extensions.py: Chứa các đối tượng mở rộng được sử dụng trong ứng dụng web.
- Tệp README.md: Tệp mô tả chi tiết về ứng dụng

**Comment by tuanhcmute** [comment]
> ### Sau khi đã thống nhất thì nhóm đã tạo ra một source code có cấu trúc như sau:
```
└── Nhom1_CCPTPM/
    ├── .circleci/
    │   └── config.yml
    ├── .github/
    │   └── FUNDING.yml
    ├── app/
    │   ├── authen/
    │   │   ├── __init__.py
    │   │   └── routes.py
    │   ├── main/
    │   │   ├── __init__.py
    │   │   └── routes.py
    │   ├── model/
    │   │   └── user.py
    │   ├── static/
    │   │   ├── css
    │   │   ├── fonts
    │   │   ├── image
    │   │   ├── js
    │   │   └── vendor
    │   ├── templates/
    │   │   ├── base.html
    │   │   ├── data.html
    │   │   ├── index.html
    │   │   ├── login.html
    │   │   └── partials/
    │   │       ├── footer.html
    │   │       ├── header.html
    │   │       └── sidebar-nav.html
    │   ├── utils/
    │   │   └── contants.py
    │   ├── vendor/
    │   │   ├── getToken.py
    │   │   └── getData.py
    │   ├── __init__.py
    │   ├── app
    │   ├── config.py
    │   └── extensions.py
    ├── test/
    │   ├── __init__.py
    │   ├── conftest.py
    │   ├── auth/
    │   │   └── test_login.py
    │   └── main/
    │       └── test_main.py
    ├── .env
    ├── .gitignore
    ├── README.md
    └── requirements.txt
```

+ .circleci => Đây là thư mục dùng để tự động test hệ thống mỗi khi code được đẩy lên github. 
+ .github => chứa những config của dự án trên github

+ app => Đây là thư mục chính chứa source code của chúng ta. Bên trong thư muc này sẽ gồm những phần như 
+ model(dùng để tạo một số model để thêm tính năng mới cho ứng dụng), 
+ thư mục static sẽ chứa code style cho trang web và một số file javascritp để tạo hiệu ứng cho trang web
+ Thư mục templates chứa phần code của html là giao diện cho ứng dụng
Và một số thư mục khác

+ tests => Đây là thư mục dùng để testcase cho ứng dụng của chúng ta bao gồm một số file python.

+ .env file cấu hình các tham số môi trường. 

+ requirements.txt => Đây là file sẽ cho chúng ta biết ứng dụng của chúng ta đang xài những thư viện gì và sẽ dùng file này để có thể install các thư viện khi mà chúng ta vừa clone dự án về.
