### ISSUE TITLE
Review các công việc đã hoàn thành trong tuần

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#9]

**Comment by MyTran2508** [comment]
### **Tổng hợp các công việc đã thực hiện trong tuần vừa qua**
##### Đã thực hiện 
> 1. Tạo tài khoản github với mail Sinh Viên. Tạo Repository cho Project
> 2. Tìm hiểu về đề tài
> - Tìm hiểu về token và cách lấy data từ token đó
> - Chọn Framework, UI, tích hợp testing và CI
> 3. Set up code
> - Tìm kiếm và triển khai template, Lấy data từ API


##### Khó khăn
> - Chưa hình dung được việc sử dụng, sàn lọc data sao cho hợp lý

**Comment by tuanhcmute** [comment]
> ## Review các công việc đã hoàn thành trong tuần
1. Sử dụng account education để có thể học tập
2. Tạo một repository cho dự án cuối kì
3. Tìm hiểu đề tài
4. Tìm hiểu một số framework, tools để thực hiện porject 
5. Setup project dựa trên một số framework và tools đã tìm hiểu
6. Thực hiện review tất cả các công việc đã hoàn thành trong tuần
